version: 2

sources:
  - name: kaggle_db
    database: KAGGLE_DB
    schema: BRONZE
    tables:
      - name: assessments 
      - name: courses 
      - name: student_assessment
      - name: student_info
      - name: student_registration
      - name: student_vle
      - name: vle