version: 2

sources:
  - name: kaggle_db
    database: KAGGLE_DB
    schema: BRONZE
    tables:
      - name: assessments 
      - name: courses 
      - name: studentassessment
      - name: studentinfo
      - name: studentregistration
      - name: studentvle
      - name: vle